/**
 * Expands vocabulary.json by adding 150 new words to levels 2, 3, and 4.
 * Level 1 remains unchanged. All duplicates removed.
 */
const fs = require('fs');
const path = require('path');

const vocabPath = path.join(__dirname, '..', 'packages', 'server', 'data', 'vocabulary.json');
const data = JSON.parse(fs.readFileSync(vocabPath, 'utf8'));

// Collect all existing english words (lowercase)
const allExisting = new Set();
for (const level of Object.values(data.levels)) {
  for (const w of level.words) allExisting.add(w.english.toLowerCase());
}
console.log('Existing total words:', allExisting.size);

// ============================================================
// LEVEL 2 NEW WORDS (w1033-w1182) - 150 words for 4th graders
// Fixed: cheerful->miserable, disappointed->hopeful, famous->fearless
// ============================================================
const level2New = [
  {id:'w1033',english:'closet',korean:'옷장',japanese:'クローゼット',chinese:'壁橱',french:'placard',spanish:'armario',german:'Schrank',category:'house',difficulty:2},
  {id:'w1034',english:'shelf',korean:'선반',japanese:'棚',chinese:'架子',french:'étagère',spanish:'estante',german:'Regal',category:'house',difficulty:2},
  {id:'w1035',english:'drawer',korean:'서랍',japanese:'引き出し',chinese:'抽屉',french:'tiroir',spanish:'cajón',german:'Schublade',category:'house',difficulty:2},
  {id:'w1036',english:'oven',korean:'오븐',japanese:'オーブン',chinese:'烤箱',french:'four',spanish:'horno',german:'Ofen',category:'house',difficulty:2},
  {id:'w1037',english:'pillow',korean:'베개',japanese:'枕',chinese:'枕头',french:'oreiller',spanish:'almohada',german:'Kissen',category:'house',difficulty:2},
  {id:'w1038',english:'sink',korean:'싱크대',japanese:'流し台',chinese:'水槽',french:'évier',spanish:'fregadero',german:'Spüle',category:'house',difficulty:2},
  {id:'w1039',english:'bathtub',korean:'욕조',japanese:'浴槽',chinese:'浴缸',french:'baignoire',spanish:'bañera',german:'Badewanne',category:'house',difficulty:2},
  {id:'w1040',english:'garage',korean:'차고',japanese:'ガレージ',chinese:'车库',french:'garage',spanish:'garaje',german:'Garage',category:'house',difficulty:2},
  {id:'w1041',english:'fence',korean:'울타리',japanese:'柵',chinese:'围栏',french:'clôture',spanish:'cerca',german:'Zaun',category:'house',difficulty:2},
  {id:'w1042',english:'basement',korean:'지하실',japanese:'地下室',chinese:'地下室',french:'sous-sol',spanish:'sótano',german:'Keller',category:'house',difficulty:2},
  {id:'w1043',english:'ceiling',korean:'천장',japanese:'天井',chinese:'天花板',french:'plafond',spanish:'techo interior',german:'Zimmerdecke',category:'house',difficulty:2},
  {id:'w1044',english:'coin',korean:'동전',japanese:'コイン',chinese:'硬币',french:'pièce',spanish:'moneda',german:'Münze',category:'house',difficulty:2},
  {id:'w1045',english:'candle',korean:'양초',japanese:'ろうそく',chinese:'蜡烛',french:'bougie',spanish:'vela',german:'Kerze',category:'house',difficulty:2},
  {id:'w1046',english:'hamburger',korean:'햄버거',japanese:'ハンバーガー',chinese:'汉堡包',french:'hamburger',spanish:'hamburguesa',german:'Hamburger',category:'food',difficulty:2},
  {id:'w1047',english:'steak',korean:'스테이크',japanese:'ステーキ',chinese:'牛排',french:'steak',spanish:'bistec',german:'Steak',category:'food',difficulty:2},
  {id:'w1048',english:'cereal',korean:'시리얼',japanese:'シリアル',chinese:'麦片',french:'céréales',spanish:'cereal',german:'Müsli',category:'food',difficulty:2},
  {id:'w1049',english:'yogurt',korean:'요구르트',japanese:'ヨーグルト',chinese:'酸奶',french:'yaourt',spanish:'yogur',german:'Joghurt',category:'food',difficulty:2},
  {id:'w1050',english:'pancake',korean:'팬케이크',japanese:'パンケーキ',chinese:'煎饼',french:'crêpe',spanish:'panqueque',german:'Pfannkuchen',category:'food',difficulty:2},
  {id:'w1051',english:'popcorn',korean:'팝콘',japanese:'ポップコーン',chinese:'爆米花',french:'pop-corn',spanish:'palomitas',german:'Popcorn',category:'food',difficulty:2},
  {id:'w1052',english:'pineapple',korean:'파인애플',japanese:'パイナップル',chinese:'菠萝',french:'ananas',spanish:'piña',german:'Ananas',category:'food',difficulty:2},
  {id:'w1053',english:'watermelon',korean:'수박',japanese:'スイカ',chinese:'西瓜',french:'pastèque',spanish:'sandía',german:'Wassermelone',category:'food',difficulty:2},
  {id:'w1054',english:'mushroom',korean:'버섯',japanese:'キノコ',chinese:'蘑菇',french:'champignon',spanish:'hongo',german:'Pilz',category:'food',difficulty:2},
  {id:'w1055',english:'pepper',korean:'후추',japanese:'コショウ',chinese:'胡椒',french:'poivre',spanish:'pimienta',german:'Pfeffer',category:'food',difficulty:2},
  {id:'w1056',english:'cucumber',korean:'오이',japanese:'キュウリ',chinese:'黄瓜',french:'concombre',spanish:'pepino',german:'Gurke',category:'food',difficulty:2},
  {id:'w1057',english:'pumpkin',korean:'호박',japanese:'カボチャ',chinese:'南瓜',french:'citrouille',spanish:'calabaza',german:'Kürbis',category:'food',difficulty:2},
  {id:'w1058',english:'lettuce',korean:'상추',japanese:'レタス',chinese:'生菜',french:'laitue',spanish:'lechuga',german:'Kopfsalat',category:'food',difficulty:2},
  {id:'w1059',english:'bacon',korean:'베이컨',japanese:'ベーコン',chinese:'培根',french:'bacon',spanish:'tocino',german:'Speck',category:'food',difficulty:2},
  {id:'w1060',english:'ham',korean:'햄',japanese:'ハム',chinese:'火腿',french:'jambon',spanish:'jamón',german:'Schinken',category:'food',difficulty:2},
  {id:'w1061',english:'swan',korean:'백조',japanese:'白鳥',chinese:'天鹅',french:'cygne',spanish:'cisne',german:'Schwan',category:'animal',difficulty:2},
  {id:'w1062',english:'owl',korean:'올빼미',japanese:'フクロウ',chinese:'猫头鹰',french:'hibou',spanish:'búho',german:'Eule',category:'animal',difficulty:2},
  {id:'w1063',english:'squirrel',korean:'다람쥐',japanese:'リス',chinese:'松鼠',french:'écureuil',spanish:'ardilla',german:'Eichhörnchen',category:'animal',difficulty:2},
  {id:'w1064',english:'seal',korean:'물개',japanese:'アザラシ',chinese:'海豹',french:'phoque',spanish:'foca',german:'Robbe',category:'animal',difficulty:2},
  {id:'w1065',english:'crab',korean:'게',japanese:'カニ',chinese:'螃蟹',french:'crabe',spanish:'cangrejo',german:'Krabbe',category:'animal',difficulty:2},
  {id:'w1066',english:'lizard',korean:'도마뱀',japanese:'トカゲ',chinese:'蜥蜴',french:'lézard',spanish:'lagarto',german:'Eidechse',category:'animal',difficulty:2},
  {id:'w1067',english:'pigeon',korean:'비둘기',japanese:'ハト',chinese:'鸽子',french:'pigeon',spanish:'paloma',german:'Taube',category:'animal',difficulty:2},
  {id:'w1068',english:'hamster',korean:'햄스터',japanese:'ハムスター',chinese:'仓鼠',french:'hamster',spanish:'hámster',german:'Hamster',category:'animal',difficulty:2},
  {id:'w1069',english:'peacock',korean:'공작새',japanese:'孔雀',chinese:'孔雀',french:'paon',spanish:'pavo real',german:'Pfau',category:'animal',difficulty:2},
  {id:'w1070',english:'ladybug',korean:'무당벌레',japanese:'テントウムシ',chinese:'瓢虫',french:'coccinelle',spanish:'mariquita',german:'Marienkäfer',category:'animal',difficulty:2},
  {id:'w1071',english:'triangle',korean:'삼각형',japanese:'三角形',chinese:'三角形',french:'triangle',spanish:'triángulo',german:'Dreieck',category:'shape',difficulty:2},
  {id:'w1072',english:'rectangle',korean:'직사각형',japanese:'長方形',chinese:'长方形',french:'rectangle',spanish:'rectángulo',german:'Rechteck',category:'shape',difficulty:2},
  {id:'w1073',english:'circle',korean:'원',japanese:'円',chinese:'圆',french:'cercle',spanish:'círculo',german:'Kreis',category:'shape',difficulty:2},
  {id:'w1074',english:'diamond',korean:'다이아몬드',japanese:'ダイヤモンド',chinese:'钻石',french:'diamant',spanish:'diamante',german:'Diamant',category:'shape',difficulty:2},
  {id:'w1075',english:'oval',korean:'타원형',japanese:'楕円',chinese:'椭圆',french:'ovale',spanish:'óvalo',german:'Oval',category:'shape',difficulty:2},
  {id:'w1076',english:'piano',korean:'피아노',japanese:'ピアノ',chinese:'钢琴',french:'piano',spanish:'piano',german:'Klavier',category:'instrument',difficulty:2},
  {id:'w1077',english:'guitar',korean:'기타',japanese:'ギター',chinese:'吉他',french:'guitare',spanish:'guitarra',german:'Gitarre',category:'instrument',difficulty:2},
  {id:'w1078',english:'violin',korean:'바이올린',japanese:'バイオリン',chinese:'小提琴',french:'violon',spanish:'violín',german:'Geige',category:'instrument',difficulty:2},
  {id:'w1079',english:'drum',korean:'드럼',japanese:'ドラム',chinese:'鼓',french:'tambour',spanish:'tambor',german:'Trommel',category:'instrument',difficulty:2},
  {id:'w1080',english:'flute',korean:'플루트',japanese:'フルート',chinese:'长笛',french:'flûte',spanish:'flauta',german:'Flöte',category:'instrument',difficulty:2},
  {id:'w1081',english:'trumpet',korean:'트럼펫',japanese:'トランペット',chinese:'小号',french:'trompette',spanish:'trompeta',german:'Trompete',category:'instrument',difficulty:2},
  {id:'w1082',english:'scissors',korean:'가위',japanese:'はさみ',chinese:'剪刀',french:'ciseaux',spanish:'tijeras',german:'Schere',category:'school',difficulty:2},
  {id:'w1083',english:'glue',korean:'풀',japanese:'のり',chinese:'胶水',french:'colle',spanish:'pegamento',german:'Klebstoff',category:'school',difficulty:2},
  {id:'w1084',english:'chalk',korean:'분필',japanese:'チョーク',chinese:'粉笔',french:'craie',spanish:'tiza',german:'Kreide',category:'school',difficulty:2},
  {id:'w1085',english:'globe',korean:'지구본',japanese:'地球儀',chinese:'地球仪',french:'globe',spanish:'globo terráqueo',german:'Globus',category:'school',difficulty:2},
  {id:'w1086',english:'elbow',korean:'팔꿈치',japanese:'肘',chinese:'肘',french:'coude',spanish:'codo',german:'Ellbogen',category:'body',difficulty:2},
  {id:'w1087',english:'toe',korean:'발가락',japanese:'つま先',chinese:'脚趾',french:'orteil',spanish:'dedo del pie',german:'Zeh',category:'body',difficulty:2},
  {id:'w1088',english:'stomach',korean:'배',japanese:'お腹',chinese:'肚子',french:'estomac',spanish:'estómago',german:'Magen',category:'body',difficulty:2},
  {id:'w1089',english:'wrist',korean:'손목',japanese:'手首',chinese:'手腕',french:'poignet',spanish:'muñeca',german:'Handgelenk',category:'body',difficulty:2},
  {id:'w1090',english:'ankle',korean:'발목',japanese:'足首',chinese:'脚踝',french:'cheville',spanish:'tobillo',german:'Knöchel',category:'body',difficulty:2},
  {id:'w1091',english:'chin',korean:'턱',japanese:'あご',chinese:'下巴',french:'menton',spanish:'barbilla',german:'Kinn',category:'body',difficulty:2},
  {id:'w1092',english:'cheek',korean:'볼',japanese:'頬',chinese:'脸颊',french:'joue',spanish:'mejilla',german:'Wange',category:'body',difficulty:2},
  {id:'w1093',english:'thumb',korean:'엄지손가락',japanese:'親指',chinese:'拇指',french:'pouce',spanish:'pulgar',german:'Daumen',category:'body',difficulty:2},
  {id:'w1094',english:'afternoon',korean:'오후',japanese:'午後',chinese:'下午',french:'après-midi',spanish:'tarde',german:'Nachmittag',category:'day',difficulty:2},
  {id:'w1095',english:'evening',korean:'저녁',japanese:'夕方',chinese:'傍晚',french:'soir',spanish:'noche',german:'Abend',category:'day',difficulty:2},
  {id:'w1096',english:'midnight',korean:'자정',japanese:'真夜中',chinese:'午夜',french:'minuit',spanish:'medianoche',german:'Mitternacht',category:'day',difficulty:2},
  {id:'w1097',english:'noon',korean:'정오',japanese:'正午',chinese:'中午',french:'midi',spanish:'mediodía',german:'Mittag',category:'day',difficulty:2},
  {id:'w1098',english:'weekend',korean:'주말',japanese:'週末',chinese:'周末',french:'week-end',spanish:'fin de semana',german:'Wochenende',category:'day',difficulty:2},
  {id:'w1099',english:'paint',korean:'칠하다',japanese:'塗る',chinese:'画',french:'peindre',spanish:'pintar',german:'malen',category:'action',difficulty:2},
  {id:'w1100',english:'fix',korean:'고치다',japanese:'修理する',chinese:'修理',french:'réparer',spanish:'reparar',german:'reparieren',category:'action',difficulty:2},
  {id:'w1101',english:'kick',korean:'차다',japanese:'蹴る',chinese:'踢',french:'donner un coup de pied',spanish:'patear',german:'treten',category:'action',difficulty:2},
  {id:'w1102',english:'knock',korean:'두드리다',japanese:'ノックする',chinese:'敲',french:'frapper',spanish:'golpear',german:'klopfen',category:'action',difficulty:2},
  {id:'w1103',english:'pour',korean:'붓다',japanese:'注ぐ',chinese:'倒',french:'verser',spanish:'verter',german:'gießen',category:'action',difficulty:2},
  {id:'w1104',english:'mix',korean:'섞다',japanese:'混ぜる',chinese:'混合',french:'mélanger',spanish:'mezclar',german:'mischen',category:'action',difficulty:2},
  {id:'w1105',english:'shake',korean:'흔들다',japanese:'振る',chinese:'摇',french:'secouer',spanish:'sacudir',german:'schütteln',category:'action',difficulty:2},
  {id:'w1106',english:'bite',korean:'물다',japanese:'噛む',chinese:'咬',french:'mordre',spanish:'morder',german:'beißen',category:'action',difficulty:2},
  {id:'w1107',english:'chew',korean:'씹다',japanese:'噛む',chinese:'嚼',french:'mâcher',spanish:'masticar',german:'kauen',category:'action',difficulty:2},
  {id:'w1108',english:'bake',korean:'굽다',japanese:'焼く',chinese:'烘焙',french:'cuire au four',spanish:'hornear',german:'backen',category:'action',difficulty:2},
  {id:'w1109',english:'boil',korean:'끓이다',japanese:'沸かす',chinese:'煮沸',french:'bouillir',spanish:'hervir',german:'kochen',category:'action',difficulty:2},
  {id:'w1110',english:'freeze',korean:'얼리다',japanese:'凍る',chinese:'冻',french:'geler',spanish:'congelar',german:'einfrieren',category:'action',difficulty:2},
  {id:'w1111',english:'melt',korean:'녹다',japanese:'溶ける',chinese:'融化',french:'fondre',spanish:'derretir',german:'schmelzen',category:'action',difficulty:2},
  {id:'w1112',english:'dig',korean:'파다',japanese:'掘る',chinese:'挖',french:'creuser',spanish:'cavar',german:'graben',category:'action',difficulty:2},
  {id:'w1113',english:'plant',korean:'심다',japanese:'植える',chinese:'种植',french:'planter',spanish:'plantar',german:'pflanzen',category:'action',difficulty:2},
  {id:'w1114',english:'feed',korean:'먹이다',japanese:'餌をやる',chinese:'喂',french:'nourrir',spanish:'alimentar',german:'füttern',category:'action',difficulty:2},
  {id:'w1115',english:'hug',korean:'안다',japanese:'抱きしめる',chinese:'拥抱',french:'serrer dans ses bras',spanish:'abrazar',german:'umarmen',category:'action',difficulty:2},
  {id:'w1116',english:'whisper',korean:'속삭이다',japanese:'ささやく',chinese:'低语',french:'chuchoter',spanish:'susurrar',german:'flüstern',category:'action',difficulty:2},
  {id:'w1117',english:'tie',korean:'묶다',japanese:'結ぶ',chinese:'系',french:'attacher',spanish:'atar',german:'binden',category:'action',difficulty:2},
  {id:'w1118',english:'hang',korean:'걸다',japanese:'掛ける',chinese:'挂',french:'accrocher',spanish:'colgar',german:'hängen',category:'action',difficulty:2},
  {id:'w1119',english:'fill',korean:'채우다',japanese:'満たす',chinese:'填满',french:'remplir',spanish:'llenar',german:'füllen',category:'action',difficulty:2},
  {id:'w1120',english:'fold',korean:'접다',japanese:'折る',chinese:'折叠',french:'plier',spanish:'doblar',german:'falten',category:'action',difficulty:2},
  {id:'w1121',english:'wrap',korean:'싸다',japanese:'包む',chinese:'包',french:'emballer',spanish:'envolver',german:'einwickeln',category:'action',difficulty:2},
  {id:'w1122',english:'stretch',korean:'늘리다',japanese:'伸ばす',chinese:'伸展',french:'étirer',spanish:'estirar',german:'dehnen',category:'action',difficulty:2},
  {id:'w1123',english:'bend',korean:'구부리다',japanese:'曲げる',chinese:'弯曲',french:'plier',spanish:'doblar',german:'biegen',category:'action',difficulty:2},
  {id:'w1124',english:'slide',korean:'미끄러지다',japanese:'滑る',chinese:'滑',french:'glisser',spanish:'deslizar',german:'rutschen',category:'action',difficulty:2},
  {id:'w1125',english:'spin',korean:'회전하다',japanese:'回転する',chinese:'旋转',french:'tourner',spanish:'girar',german:'drehen',category:'action',difficulty:2},
  {id:'w1126',english:'wave',korean:'손을 흔들다',japanese:'手を振る',chinese:'挥手',french:'agiter',spanish:'agitar la mano',german:'winken',category:'action',difficulty:2},
  {id:'w1127',english:'point',korean:'가리키다',japanese:'指さす',chinese:'指',french:'montrer du doigt',spanish:'señalar',german:'zeigen',category:'action',difficulty:2},
  {id:'w1128',english:'guess',korean:'추측하다',japanese:'推測する',chinese:'猜',french:'deviner',spanish:'adivinar',german:'raten',category:'action',difficulty:2},
  // Emotions - replaced cheerful->miserable, disappointed->hopeful
  {id:'w1129',english:'shy',korean:'수줍은',japanese:'恥ずかしがり屋',chinese:'害羞的',french:'timide',spanish:'tímido',german:'schüchtern',category:'emotion',difficulty:2},
  {id:'w1130',english:'rude',korean:'무례한',japanese:'失礼な',chinese:'粗鲁的',french:'impoli',spanish:'grosero',german:'unhöflich',category:'emotion',difficulty:2},
  {id:'w1131',english:'selfish',korean:'이기적인',japanese:'利己的な',chinese:'自私的',french:'égoïste',spanish:'egoísta',german:'egoistisch',category:'emotion',difficulty:2},
  {id:'w1132',english:'calm',korean:'차분한',japanese:'穏やかな',chinese:'冷静的',french:'calme',spanish:'calmado',german:'ruhig',category:'emotion',difficulty:2},
  {id:'w1133',english:'miserable',korean:'비참한',japanese:'惨めな',chinese:'悲惨的',french:'misérable',spanish:'miserable',german:'elend',category:'emotion',difficulty:2},
  {id:'w1134',english:'hopeful',korean:'희망에 찬',japanese:'希望に満ちた',chinese:'充满希望的',french:'plein d\'espoir',spanish:'esperanzado',german:'hoffnungsvoll',category:'emotion',difficulty:2},
  {id:'w1135',english:'embarrassed',korean:'당황한',japanese:'恥ずかしい',chinese:'尴尬的',french:'gêné',spanish:'avergonzado',german:'verlegen',category:'emotion',difficulty:2},
  {id:'w1136',english:'satisfied',korean:'만족한',japanese:'満足した',chinese:'满意的',french:'satisfait',spanish:'satisfecho',german:'zufrieden',category:'emotion',difficulty:2},
  {id:'w1137',english:'annoyed',korean:'짜증난',japanese:'いらいらした',chinese:'烦恼的',french:'agacé',spanish:'molesto',german:'genervt',category:'emotion',difficulty:2},
  // Adjectives - replaced famous->fearless
  {id:'w1138',english:'empty',korean:'빈',japanese:'空の',chinese:'空的',french:'vide',spanish:'vacío',german:'leer',category:'adjective',difficulty:2},
  {id:'w1139',english:'full',korean:'가득 찬',japanese:'満杯の',chinese:'满的',french:'plein',spanish:'lleno',german:'voll',category:'adjective',difficulty:2},
  {id:'w1140',english:'fresh',korean:'신선한',japanese:'新鮮な',chinese:'新鲜的',french:'frais',spanish:'fresco',german:'frisch',category:'adjective',difficulty:2},
  {id:'w1141',english:'delicious',korean:'맛있는',japanese:'おいしい',chinese:'美味的',french:'délicieux',spanish:'delicioso',german:'köstlich',category:'adjective',difficulty:2},
  {id:'w1142',english:'spicy',korean:'매운',japanese:'辛い',chinese:'辣的',french:'épicé',spanish:'picante',german:'scharf',category:'adjective',difficulty:2},
  {id:'w1143',english:'bitter',korean:'쓴',japanese:'苦い',chinese:'苦的',french:'amer',spanish:'amargo',german:'bitter',category:'adjective',difficulty:2},
  {id:'w1144',english:'warm',korean:'따뜻한',japanese:'暖かい',chinese:'温暖的',french:'chaud',spanish:'cálido',german:'warm',category:'adjective',difficulty:2},
  {id:'w1145',english:'cool',korean:'시원한',japanese:'涼しい',chinese:'凉爽的',french:'frais',spanish:'fresco',german:'kühl',category:'adjective',difficulty:2},
  {id:'w1146',english:'straight',korean:'곧은',japanese:'まっすぐな',chinese:'直的',french:'droit',spanish:'recto',german:'gerade',category:'adjective',difficulty:2},
  {id:'w1147',english:'loose',korean:'느슨한',japanese:'ゆるい',chinese:'松的',french:'lâche',spanish:'suelto',german:'locker',category:'adjective',difficulty:2},
  {id:'w1148',english:'tight',korean:'꽉 끼는',japanese:'きつい',chinese:'紧的',french:'serré',spanish:'apretado',german:'eng',category:'adjective',difficulty:2},
  {id:'w1149',english:'whole',korean:'전체의',japanese:'全体の',chinese:'整个的',french:'entier',spanish:'entero',german:'ganz',category:'adjective',difficulty:2},
  {id:'w1150',english:'half',korean:'반',japanese:'半分',chinese:'一半',french:'moitié',spanish:'mitad',german:'halb',category:'adjective',difficulty:2},
  {id:'w1151',english:'absent',korean:'결석한',japanese:'欠席の',chinese:'缺席的',french:'absent',spanish:'ausente',german:'abwesend',category:'adjective',difficulty:2},
  {id:'w1152',english:'opposite',korean:'반대의',japanese:'反対の',chinese:'相反的',french:'opposé',spanish:'opuesto',german:'gegenüber',category:'adjective',difficulty:2},
  {id:'w1153',english:'similar',korean:'비슷한',japanese:'似ている',chinese:'相似的',french:'similaire',spanish:'similar',german:'ähnlich',category:'adjective',difficulty:2},
  {id:'w1154',english:'different',korean:'다른',japanese:'異なる',chinese:'不同的',french:'différent',spanish:'diferente',german:'verschieden',category:'adjective',difficulty:2},
  {id:'w1155',english:'wrong',korean:'틀린',japanese:'間違った',chinese:'错误的',french:'faux',spanish:'equivocado',german:'falsch',category:'adjective',difficulty:2},
  {id:'w1156',english:'possible',korean:'가능한',japanese:'可能な',chinese:'可能的',french:'possible',spanish:'posible',german:'möglich',category:'adjective',difficulty:2},
  {id:'w1157',english:'real',korean:'진짜의',japanese:'本当の',chinese:'真实的',french:'réel',spanish:'real',german:'echt',category:'adjective',difficulty:2},
  {id:'w1158',english:'pocket',korean:'주머니',japanese:'ポケット',chinese:'口袋',french:'poche',spanish:'bolsillo',german:'Tasche',category:'clothing',difficulty:2},
  {id:'w1159',english:'zipper',korean:'지퍼',japanese:'ジッパー',chinese:'拉链',french:'fermeture éclair',spanish:'cremallera',german:'Reißverschluss',category:'clothing',difficulty:2},
  {id:'w1160',english:'button',korean:'단추',japanese:'ボタン',chinese:'纽扣',french:'bouton',spanish:'botón',german:'Knopf',category:'clothing',difficulty:2},
  {id:'w1161',english:'ribbon',korean:'리본',japanese:'リボン',chinese:'丝带',french:'ruban',spanish:'cinta',german:'Band',category:'clothing',difficulty:2},
  {id:'w1162',english:'pond',korean:'연못',japanese:'池',chinese:'池塘',french:'étang',spanish:'estanque',german:'Teich',category:'nature',difficulty:2},
  {id:'w1163',english:'hill',korean:'언덕',japanese:'丘',chinese:'小山',french:'colline',spanish:'colina',german:'Hügel',category:'nature',difficulty:2},
  {id:'w1164',english:'field',korean:'들판',japanese:'野原',chinese:'田野',french:'champ',spanish:'campo',german:'Feld',category:'nature',difficulty:2},
  {id:'w1165',english:'branch',korean:'나뭇가지',japanese:'枝',chinese:'树枝',french:'branche',spanish:'rama',german:'Zweig',category:'nature',difficulty:2},
  {id:'w1166',english:'root',korean:'뿌리',japanese:'根',chinese:'根',french:'racine',spanish:'raíz',german:'Wurzel',category:'nature',difficulty:2},
  {id:'w1167',english:'mud',korean:'진흙',japanese:'泥',chinese:'泥',french:'boue',spanish:'barro',german:'Schlamm',category:'nature',difficulty:2},
  {id:'w1168',english:'sand',korean:'모래',japanese:'砂',chinese:'沙子',french:'sable',spanish:'arena',german:'Sand',category:'nature',difficulty:2},
  {id:'w1169',english:'shadow',korean:'그림자',japanese:'影',chinese:'影子',french:'ombre',spanish:'sombra',german:'Schatten',category:'nature',difficulty:2},
  {id:'w1170',english:'sunset',korean:'일몰',japanese:'日没',chinese:'日落',french:'coucher de soleil',spanish:'puesta de sol',german:'Sonnenuntergang',category:'nature',difficulty:2},
  {id:'w1171',english:'sunrise',korean:'일출',japanese:'日の出',chinese:'日出',french:'lever de soleil',spanish:'amanecer',german:'Sonnenaufgang',category:'nature',difficulty:2},
  {id:'w1172',english:'strange',korean:'이상한',japanese:'奇妙な',chinese:'奇怪的',french:'étrange',spanish:'extraño',german:'seltsam',category:'adjective',difficulty:2},
  {id:'w1173',english:'silly',korean:'바보 같은',japanese:'ばかな',chinese:'傻的',french:'bête',spanish:'tonto',german:'albern',category:'adjective',difficulty:2},
  {id:'w1174',english:'wise',korean:'현명한',japanese:'賢い',chinese:'明智的',french:'sage',spanish:'sabio',german:'weise',category:'adjective',difficulty:2},
  {id:'w1175',english:'usual',korean:'평소의',japanese:'普通の',chinese:'通常的',french:'habituel',spanish:'habitual',german:'üblich',category:'adjective',difficulty:2},
  {id:'w1176',english:'fearless',korean:'겁 없는',japanese:'恐れを知らない',chinese:'无畏的',french:'intrépide',spanish:'intrépido',german:'furchtlos',category:'adjective',difficulty:2},
  {id:'w1177',english:'awake',korean:'깨어 있는',japanese:'起きている',chinese:'醒着的',french:'éveillé',spanish:'despierto',german:'wach',category:'adjective',difficulty:2},
  {id:'w1178',english:'asleep',korean:'잠든',japanese:'眠っている',chinese:'睡着的',french:'endormi',spanish:'dormido',german:'schlafend',category:'adjective',difficulty:2},
  {id:'w1179',english:'alive',korean:'살아 있는',japanese:'生きている',chinese:'活着的',french:'vivant',spanish:'vivo',german:'lebendig',category:'adjective',difficulty:2},
  {id:'w1180',english:'dead',korean:'죽은',japanese:'死んだ',chinese:'死的',french:'mort',spanish:'muerto',german:'tot',category:'adjective',difficulty:2},
  {id:'w1181',english:'ready',korean:'준비된',japanese:'準備ができた',chinese:'准备好的',french:'prêt',spanish:'listo',german:'bereit',category:'adjective',difficulty:2},
  {id:'w1182',english:'busy',korean:'바쁜',japanese:'忙しい',chinese:'忙碌的',french:'occupé',spanish:'ocupado',german:'beschäftigt',category:'adjective',difficulty:2},
];

// ============================================================
// LEVEL 3 NEW WORDS (w1183-w1332) - 150 words for 5th graders
// All duplicates replaced with unique words
// ============================================================
const level3New = [
  {id:'w1183',english:'peninsula',korean:'반도',japanese:'半島',chinese:'半岛',french:'péninsule',spanish:'península',german:'Halbinsel',category:'nature',difficulty:3},
  {id:'w1184',english:'latitude',korean:'위도',japanese:'緯度',chinese:'纬度',french:'latitude',spanish:'latitud',german:'Breitengrad',category:'nature',difficulty:3},
  {id:'w1185',english:'longitude',korean:'경도',japanese:'経度',chinese:'经度',french:'longitude',spanish:'longitud',german:'Längengrad',category:'nature',difficulty:3},
  {id:'w1186',english:'volcano',korean:'화산',japanese:'火山',chinese:'火山',french:'volcan',spanish:'volcán',german:'Vulkan',category:'nature',difficulty:3},
  {id:'w1187',english:'earthquake',korean:'지진',japanese:'地震',chinese:'地震',french:'tremblement de terre',spanish:'terremoto',german:'Erdbeben',category:'nature',difficulty:3},
  {id:'w1188',english:'plateau',korean:'고원',japanese:'高原',chinese:'高原',french:'plateau',spanish:'meseta',german:'Hochebene',category:'nature',difficulty:3},
  {id:'w1189',english:'canyon',korean:'협곡',japanese:'峡谷',chinese:'峡谷',french:'canyon',spanish:'cañón',german:'Schlucht',category:'nature',difficulty:3},
  {id:'w1190',english:'swamp',korean:'늪',japanese:'沼',chinese:'沼泽',french:'marais',spanish:'pantano',german:'Sumpf',category:'nature',difficulty:3},
  {id:'w1191',english:'coast',korean:'해안',japanese:'海岸',chinese:'海岸',french:'côte',spanish:'costa',german:'Küste',category:'nature',difficulty:3},
  {id:'w1192',english:'cliff',korean:'절벽',japanese:'崖',chinese:'悬崖',french:'falaise',spanish:'acantilado',german:'Klippe',category:'nature',difficulty:3},
  {id:'w1193',english:'oxygen',korean:'산소',japanese:'酸素',chinese:'氧气',french:'oxygène',spanish:'oxígeno',german:'Sauerstoff',category:'science',difficulty:3},
  {id:'w1194',english:'carbon',korean:'탄소',japanese:'炭素',chinese:'碳',french:'carbone',spanish:'carbono',german:'Kohlenstoff',category:'science',difficulty:3},
  {id:'w1195',english:'mineral',korean:'광물',japanese:'鉱物',chinese:'矿物',french:'minéral',spanish:'mineral',german:'Mineral',category:'science',difficulty:3},
  {id:'w1196',english:'solar',korean:'태양의',japanese:'太陽の',chinese:'太阳的',french:'solaire',spanish:'solar',german:'solar',category:'science',difficulty:3},
  {id:'w1197',english:'lunar',korean:'달의',japanese:'月の',chinese:'月球的',french:'lunaire',spanish:'lunar',german:'Mond-',category:'science',difficulty:3},
  {id:'w1198',english:'orbit',korean:'궤도',japanese:'軌道',chinese:'轨道',french:'orbite',spanish:'órbita',german:'Umlaufbahn',category:'science',difficulty:3},
  {id:'w1199',english:'species',korean:'종',japanese:'種',chinese:'物种',french:'espèce',spanish:'especie',german:'Art',category:'science',difficulty:3},
  {id:'w1200',english:'magnetic',korean:'자기의',japanese:'磁気の',chinese:'磁性的',french:'magnétique',spanish:'magnético',german:'magnetisch',category:'science',difficulty:3},
  {id:'w1201',english:'specimen',korean:'표본',japanese:'標本',chinese:'标本',french:'spécimen',spanish:'espécimen',german:'Exemplar',category:'science',difficulty:3},
  {id:'w1202',english:'radiation',korean:'방사선',japanese:'放射線',chinese:'辐射',french:'radiation',spanish:'radiación',german:'Strahlung',category:'science',difficulty:3},
  {id:'w1203',english:'cell',korean:'세포',japanese:'細胞',chinese:'细胞',french:'cellule',spanish:'célula',german:'Zelle',category:'science',difficulty:3},
  {id:'w1204',english:'nucleus',korean:'핵',japanese:'核',chinese:'原子核',french:'noyau',spanish:'núcleo',german:'Kern',category:'science',difficulty:3},
  {id:'w1205',english:'microbe',korean:'미생물',japanese:'微生物',chinese:'微生物',french:'microbe',spanish:'microbio',german:'Mikrobe',category:'science',difficulty:3},
  {id:'w1206',english:'virus',korean:'바이러스',japanese:'ウイルス',chinese:'病毒',french:'virus',spanish:'virus',german:'Virus',category:'science',difficulty:3},
  {id:'w1207',english:'photosynthesis',korean:'광합성',japanese:'光合成',chinese:'光合作用',french:'photosynthèse',spanish:'fotosíntesis',german:'Photosynthese',category:'science',difficulty:3},
  {id:'w1208',english:'tradition',korean:'전통',japanese:'伝統',chinese:'传统',french:'tradition',spanish:'tradición',german:'Tradition',category:'society',difficulty:3},
  {id:'w1209',english:'festival',korean:'축제',japanese:'祭り',chinese:'节日',french:'festival',spanish:'festival',german:'Festival',category:'society',difficulty:3},
  {id:'w1210',english:'monument',korean:'기념물',japanese:'記念碑',chinese:'纪念碑',french:'monument',spanish:'monumento',german:'Denkmal',category:'society',difficulty:3},
  {id:'w1211',english:'ritual',korean:'의례',japanese:'儀式',chinese:'仪式',french:'rituel',spanish:'ritual',german:'Ritual',category:'society',difficulty:3},
  {id:'w1212',english:'community',korean:'공동체',japanese:'コミュニティ',chinese:'社区',french:'communauté',spanish:'comunidad',german:'Gemeinschaft',category:'society',difficulty:3},
  {id:'w1213',english:'religion',korean:'종교',japanese:'宗教',chinese:'宗教',french:'religion',spanish:'religión',german:'Religion',category:'society',difficulty:3},
  {id:'w1214',english:'poverty',korean:'빈곤',japanese:'貧困',chinese:'贫困',french:'pauvreté',spanish:'pobreza',german:'Armut',category:'society',difficulty:3},
  {id:'w1215',english:'wealth',korean:'부',japanese:'富',chinese:'财富',french:'richesse',spanish:'riqueza',german:'Reichtum',category:'society',difficulty:3},
  {id:'w1216',english:'justice',korean:'정의',japanese:'正義',chinese:'正义',french:'justice',spanish:'justicia',german:'Gerechtigkeit',category:'society',difficulty:3},
  {id:'w1217',english:'protest',korean:'항의',japanese:'抗議',chinese:'抗议',french:'protestation',spanish:'protesta',german:'Protest',category:'society',difficulty:3},
  {id:'w1218',english:'slavery',korean:'노예제도',japanese:'奴隷制',chinese:'奴隶制',french:'esclavage',spanish:'esclavitud',german:'Sklaverei',category:'society',difficulty:3},
  {id:'w1219',english:'republic',korean:'공화국',japanese:'共和国',chinese:'共和国',french:'république',spanish:'república',german:'Republik',category:'society',difficulty:3},
  {id:'w1220',english:'independence',korean:'독립',japanese:'独立',chinese:'独立',french:'indépendance',spanish:'independencia',german:'Unabhängigkeit',category:'society',difficulty:3},
  {id:'w1221',english:'empire',korean:'제국',japanese:'帝国',chinese:'帝国',french:'empire',spanish:'imperio',german:'Imperium',category:'society',difficulty:3},
  {id:'w1222',english:'treaty',korean:'조약',japanese:'条約',chinese:'条约',french:'traité',spanish:'tratado',german:'Vertrag',category:'society',difficulty:3},
  {id:'w1223',english:'ambitious',korean:'야심 있는',japanese:'野心的な',chinese:'有抱负的',french:'ambitieux',spanish:'ambicioso',german:'ehrgeizig',category:'emotion',difficulty:3},
  {id:'w1224',english:'humble',korean:'겸손한',japanese:'謙虚な',chinese:'谦虚的',french:'humble',spanish:'humilde',german:'bescheiden',category:'emotion',difficulty:3},
  {id:'w1225',english:'stubborn',korean:'완고한',japanese:'頑固な',chinese:'固执的',french:'têtu',spanish:'terco',german:'stur',category:'emotion',difficulty:3},
  {id:'w1226',english:'creative',korean:'창의적인',japanese:'創造的な',chinese:'创造性的',french:'créatif',spanish:'creativo',german:'kreativ',category:'emotion',difficulty:3},
  {id:'w1227',english:'reliable',korean:'신뢰할 수 있는',japanese:'信頼できる',chinese:'可靠的',french:'fiable',spanish:'confiable',german:'zuverlässig',category:'emotion',difficulty:3},
  {id:'w1228',english:'sensitive',korean:'민감한',japanese:'繊細な',chinese:'敏感的',french:'sensible',spanish:'sensible',german:'empfindlich',category:'emotion',difficulty:3},
  {id:'w1229',english:'optimistic',korean:'낙관적인',japanese:'楽観的な',chinese:'乐观的',french:'optimiste',spanish:'optimista',german:'optimistisch',category:'emotion',difficulty:3},
  {id:'w1230',english:'pessimistic',korean:'비관적인',japanese:'悲観的な',chinese:'悲观的',french:'pessimiste',spanish:'pesimista',german:'pessimistisch',category:'emotion',difficulty:3},
  {id:'w1231',english:'sympathy',korean:'동정',japanese:'同情',chinese:'同情',french:'sympathie',spanish:'simpatía',german:'Sympathie',category:'emotion',difficulty:3},
  {id:'w1232',english:'dignity',korean:'존엄성',japanese:'尊厳',chinese:'尊严',french:'dignité',spanish:'dignidad',german:'Würde',category:'emotion',difficulty:3},
  {id:'w1233',english:'predict',korean:'예측하다',japanese:'予測する',chinese:'预测',french:'prédire',spanish:'predecir',german:'vorhersagen',category:'action',difficulty:3},
  {id:'w1234',english:'observe',korean:'관찰하다',japanese:'観察する',chinese:'观察',french:'observer',spanish:'observar',german:'beobachten',category:'action',difficulty:3},
  {id:'w1235',english:'research',korean:'연구하다',japanese:'研究する',chinese:'研究',french:'rechercher',spanish:'investigar',german:'forschen',category:'action',difficulty:3},
  {id:'w1236',english:'measure',korean:'측정하다',japanese:'測定する',chinese:'测量',french:'mesurer',spanish:'medir',german:'messen',category:'action',difficulty:3},
  {id:'w1237',english:'organize',korean:'정리하다',japanese:'整理する',chinese:'组织',french:'organiser',spanish:'organizar',german:'organisieren',category:'action',difficulty:3},
  {id:'w1238',english:'represent',korean:'대표하다',japanese:'代表する',chinese:'代表',french:'représenter',spanish:'representar',german:'vertreten',category:'action',difficulty:3},
  {id:'w1239',english:'persuade',korean:'설득하다',japanese:'説得する',chinese:'说服',french:'persuader',spanish:'persuadir',german:'überreden',category:'action',difficulty:3},
  {id:'w1240',english:'sacrifice',korean:'희생하다',japanese:'犠牲にする',chinese:'牺牲',french:'sacrifier',spanish:'sacrificar',german:'opfern',category:'action',difficulty:3},
  {id:'w1241',english:'translate',korean:'번역하다',japanese:'翻訳する',chinese:'翻译',french:'traduire',spanish:'traducir',german:'übersetzen',category:'action',difficulty:3},
  {id:'w1242',english:'publish',korean:'출판하다',japanese:'出版する',chinese:'出版',french:'publier',spanish:'publicar',german:'veröffentlichen',category:'action',difficulty:3},
  {id:'w1243',english:'react',korean:'반응하다',japanese:'反応する',chinese:'反应',french:'réagir',spanish:'reaccionar',german:'reagieren',category:'action',difficulty:3},
  {id:'w1244',english:'resolve',korean:'해결하다',japanese:'解決する',chinese:'解决',french:'résoudre',spanish:'resolver',german:'lösen',category:'action',difficulty:3},
  {id:'w1245',english:'allocate',korean:'할당하다',japanese:'割り当てる',chinese:'分配',french:'allouer',spanish:'asignar',german:'zuteilen',category:'action',difficulty:3},
  {id:'w1246',english:'evaluate',korean:'평가하다',japanese:'評価する',chinese:'评估',french:'évaluer',spanish:'evaluar',german:'bewerten',category:'action',difficulty:3},
  {id:'w1247',english:'classify',korean:'분류하다',japanese:'分類する',chinese:'分类',french:'classer',spanish:'clasificar',german:'klassifizieren',category:'action',difficulty:3},
  {id:'w1248',english:'internet',korean:'인터넷',japanese:'インターネット',chinese:'互联网',french:'internet',spanish:'internet',german:'Internet',category:'technology',difficulty:3},
  {id:'w1249',english:'keyboard',korean:'키보드',japanese:'キーボード',chinese:'键盘',french:'clavier',spanish:'teclado',german:'Tastatur',category:'technology',difficulty:3},
  {id:'w1250',english:'monitor',korean:'모니터',japanese:'モニター',chinese:'显示器',french:'moniteur',spanish:'monitor',german:'Monitor',category:'technology',difficulty:3},
  {id:'w1251',english:'website',korean:'웹사이트',japanese:'ウェブサイト',chinese:'网站',french:'site web',spanish:'sitio web',german:'Webseite',category:'technology',difficulty:3},
  {id:'w1252',english:'software',korean:'소프트웨어',japanese:'ソフトウェア',chinese:'软件',french:'logiciel',spanish:'software',german:'Software',category:'technology',difficulty:3},
  {id:'w1253',english:'hardware',korean:'하드웨어',japanese:'ハードウェア',chinese:'硬件',french:'matériel',spanish:'hardware',german:'Hardware',category:'technology',difficulty:3},
  {id:'w1254',english:'program',korean:'프로그램',japanese:'プログラム',chinese:'程序',french:'programme',spanish:'programa',german:'Programm',category:'technology',difficulty:3},
  {id:'w1255',english:'download',korean:'다운로드',japanese:'ダウンロード',chinese:'下载',french:'télécharger',spanish:'descargar',german:'herunterladen',category:'technology',difficulty:3},
  {id:'w1256',english:'upload',korean:'업로드',japanese:'アップロード',chinese:'上传',french:'téléverser',spanish:'subir',german:'hochladen',category:'technology',difficulty:3},
  {id:'w1257',english:'password',korean:'비밀번호',japanese:'パスワード',chinese:'密码',french:'mot de passe',spanish:'contraseña',german:'Passwort',category:'technology',difficulty:3},
  {id:'w1258',english:'symptom',korean:'증상',japanese:'症状',chinese:'症状',french:'symptôme',spanish:'síntoma',german:'Symptom',category:'science',difficulty:3},
  {id:'w1259',english:'treatment',korean:'치료',japanese:'治療',chinese:'治疗',french:'traitement',spanish:'tratamiento',german:'Behandlung',category:'science',difficulty:3},
  {id:'w1260',english:'allergy',korean:'알레르기',japanese:'アレルギー',chinese:'过敏',french:'allergie',spanish:'alergia',german:'Allergie',category:'science',difficulty:3},
  {id:'w1261',english:'nutrition',korean:'영양',japanese:'栄養',chinese:'营养',french:'nutrition',spanish:'nutrición',german:'Ernährung',category:'science',difficulty:3},
  {id:'w1262',english:'vitamin',korean:'비타민',japanese:'ビタミン',chinese:'维生素',french:'vitamine',spanish:'vitamina',german:'Vitamin',category:'science',difficulty:3},
  {id:'w1263',english:'diet',korean:'식단',japanese:'ダイエット',chinese:'饮食',french:'régime',spanish:'dieta',german:'Diät',category:'science',difficulty:3},
  {id:'w1264',english:'infection',korean:'감염',japanese:'感染',chinese:'感染',french:'infection',spanish:'infección',german:'Infektion',category:'science',difficulty:3},
  {id:'w1265',english:'surgery',korean:'수술',japanese:'手術',chinese:'手术',french:'chirurgie',spanish:'cirugía',german:'Operation',category:'science',difficulty:3},
  {id:'w1266',english:'vaccine',korean:'백신',japanese:'ワクチン',chinese:'疫苗',french:'vaccin',spanish:'vacuna',german:'Impfstoff',category:'science',difficulty:3},
  {id:'w1267',english:'prescription',korean:'처방전',japanese:'処方箋',chinese:'处方',french:'ordonnance',spanish:'receta médica',german:'Rezept',category:'science',difficulty:3},
  {id:'w1268',english:'price',korean:'가격',japanese:'価格',chinese:'价格',french:'prix',spanish:'precio',german:'Preis',category:'society',difficulty:3},
  {id:'w1269',english:'cost',korean:'비용',japanese:'費用',chinese:'成本',french:'coût',spanish:'costo',german:'Kosten',category:'society',difficulty:3},
  {id:'w1270',english:'profit',korean:'이윤',japanese:'利益',chinese:'利润',french:'profit',spanish:'ganancia',german:'Gewinn',category:'society',difficulty:3},
  {id:'w1271',english:'savings',korean:'저축',japanese:'貯金',chinese:'储蓄',french:'épargne',spanish:'ahorros',german:'Ersparnisse',category:'society',difficulty:3},
  {id:'w1272',english:'tax',korean:'세금',japanese:'税金',chinese:'税',french:'impôt',spanish:'impuesto',german:'Steuer',category:'society',difficulty:3},
  {id:'w1273',english:'wage',korean:'임금',japanese:'賃金',chinese:'工资',french:'salaire',spanish:'salario',german:'Lohn',category:'society',difficulty:3},
  {id:'w1274',english:'debt',korean:'빚',japanese:'借金',chinese:'债务',french:'dette',spanish:'deuda',german:'Schulden',category:'society',difficulty:3},
  {id:'w1275',english:'loan',korean:'대출',japanese:'ローン',chinese:'贷款',french:'prêt',spanish:'préstamo',german:'Darlehen',category:'society',difficulty:3},
  {id:'w1276',english:'invest',korean:'투자하다',japanese:'投資する',chinese:'投资',french:'investir',spanish:'invertir',german:'investieren',category:'society',difficulty:3},
  {id:'w1277',english:'merchant',korean:'상인',japanese:'商人',chinese:'商人',french:'marchand',spanish:'comerciante',german:'Händler',category:'society',difficulty:3},
  {id:'w1278',english:'sculpture',korean:'조각',japanese:'彫刻',chinese:'雕塑',french:'sculpture',spanish:'escultura',german:'Skulptur',category:'education',difficulty:3},
  {id:'w1279',english:'pottery',korean:'도자기',japanese:'陶器',chinese:'陶器',french:'poterie',spanish:'cerámica',german:'Töpferei',category:'education',difficulty:3},
  {id:'w1280',english:'gallery',korean:'갤러리',japanese:'ギャラリー',chinese:'画廊',french:'galerie',spanish:'galería',german:'Galerie',category:'education',difficulty:3},
  {id:'w1281',english:'exhibition',korean:'전시회',japanese:'展示会',chinese:'展览',french:'exposition',spanish:'exposición',german:'Ausstellung',category:'education',difficulty:3},
  {id:'w1282',english:'canvas',korean:'캔버스',japanese:'キャンバス',chinese:'画布',french:'toile',spanish:'lienzo',german:'Leinwand',category:'education',difficulty:3},
  {id:'w1283',english:'portrait',korean:'초상화',japanese:'肖像画',chinese:'肖像',french:'portrait',spanish:'retrato',german:'Porträt',category:'education',difficulty:3},
  {id:'w1284',english:'landscape',korean:'풍경',japanese:'風景',chinese:'风景',french:'paysage',spanish:'paisaje',german:'Landschaft',category:'education',difficulty:3},
  {id:'w1285',english:'sketch',korean:'스케치',japanese:'スケッチ',chinese:'素描',french:'croquis',spanish:'boceto',german:'Skizze',category:'education',difficulty:3},
  {id:'w1286',english:'melody',korean:'멜로디',japanese:'メロディー',chinese:'旋律',french:'mélodie',spanish:'melodía',german:'Melodie',category:'education',difficulty:3},
  {id:'w1287',english:'rhythm',korean:'리듬',japanese:'リズム',chinese:'节奏',french:'rythme',spanish:'ritmo',german:'Rhythmus',category:'education',difficulty:3},
  {id:'w1288',english:'pollution',korean:'오염',japanese:'汚染',chinese:'污染',french:'pollution',spanish:'contaminación',german:'Verschmutzung',category:'nature',difficulty:3},
  {id:'w1289',english:'recycle',korean:'재활용하다',japanese:'リサイクルする',chinese:'回收',french:'recycler',spanish:'reciclar',german:'recyceln',category:'nature',difficulty:3},
  {id:'w1290',english:'renewable',korean:'재생 가능한',japanese:'再生可能な',chinese:'可再生的',french:'renouvelable',spanish:'renovable',german:'erneuerbar',category:'nature',difficulty:3},
  {id:'w1291',english:'deforestation',korean:'산림 벌채',japanese:'森林伐採',chinese:'砍伐森林',french:'déforestation',spanish:'deforestación',german:'Abholzung',category:'nature',difficulty:3},
  {id:'w1292',english:'endangered',korean:'멸종 위기의',japanese:'絶滅危惧の',chinese:'濒危的',french:'en voie de disparition',spanish:'en peligro',german:'gefährdet',category:'nature',difficulty:3},
  {id:'w1293',english:'extinction',korean:'멸종',japanese:'絶滅',chinese:'灭绝',french:'extinction',spanish:'extinción',german:'Aussterben',category:'nature',difficulty:3},
  {id:'w1294',english:'carbon dioxide',korean:'이산화탄소',japanese:'二酸化炭素',chinese:'二氧化碳',french:'dioxyde de carbone',spanish:'dióxido de carbono',german:'Kohlendioxid',category:'science',difficulty:3},
  {id:'w1295',english:'preserve',korean:'보존하다',japanese:'保存する',chinese:'保护',french:'préserver',spanish:'preservar',german:'bewahren',category:'action',difficulty:3},
  {id:'w1296',english:'sustain',korean:'유지하다',japanese:'維持する',chinese:'维持',french:'soutenir',spanish:'sostener',german:'aufrechterhalten',category:'action',difficulty:3},
  {id:'w1297',english:'visible',korean:'눈에 보이는',japanese:'目に見える',chinese:'可见的',french:'visible',spanish:'visible',german:'sichtbar',category:'adjective',difficulty:3},
  {id:'w1298',english:'invisible',korean:'눈에 보이지 않는',japanese:'目に見えない',chinese:'看不见的',french:'invisible',spanish:'invisible',german:'unsichtbar',category:'adjective',difficulty:3},
  {id:'w1299',english:'obvious',korean:'명백한',japanese:'明らかな',chinese:'明显的',french:'évident',spanish:'obvio',german:'offensichtlich',category:'adjective',difficulty:3},
  {id:'w1300',english:'transparent',korean:'투명한',japanese:'透明な',chinese:'透明的',french:'transparent',spanish:'transparente',german:'transparent',category:'adjective',difficulty:3},
  {id:'w1301',english:'temporary',korean:'일시적인',japanese:'一時的な',chinese:'临时的',french:'temporaire',spanish:'temporal',german:'vorübergehend',category:'adjective',difficulty:3},
  {id:'w1302',english:'permanent',korean:'영구적인',japanese:'永久的な',chinese:'永久的',french:'permanent',spanish:'permanente',german:'dauerhaft',category:'adjective',difficulty:3},
  {id:'w1303',english:'relevant',korean:'관련 있는',japanese:'関連のある',chinese:'相关的',french:'pertinent',spanish:'relevante',german:'relevant',category:'adjective',difficulty:3},
  {id:'w1304',english:'sufficient',korean:'충분한',japanese:'十分な',chinese:'充分的',french:'suffisant',spanish:'suficiente',german:'ausreichend',category:'adjective',difficulty:3},
  {id:'w1305',english:'abundant',korean:'풍부한',japanese:'豊富な',chinese:'丰富的',french:'abondant',spanish:'abundante',german:'reichlich',category:'adjective',difficulty:3},
  {id:'w1306',english:'scarce',korean:'부족한',japanese:'乏しい',chinese:'稀缺的',french:'rare',spanish:'escaso',german:'knapp',category:'adjective',difficulty:3},
  {id:'w1307',english:'moderate',korean:'적당한',japanese:'穏やかな',chinese:'适度的',french:'modéré',spanish:'moderado',german:'mäßig',category:'adjective',difficulty:3},
  {id:'w1308',english:'intense',korean:'강렬한',japanese:'激しい',chinese:'强烈的',french:'intense',spanish:'intenso',german:'intensiv',category:'adjective',difficulty:3},
  {id:'w1309',english:'precise',korean:'정밀한',japanese:'精密な',chinese:'精确的',french:'précis',spanish:'preciso',german:'präzise',category:'adjective',difficulty:3},
  {id:'w1310',english:'vague',korean:'모호한',japanese:'あいまいな',chinese:'模糊的',french:'vague',spanish:'vago',german:'vage',category:'adjective',difficulty:3},
  {id:'w1311',english:'genuine',korean:'진짜의',japanese:'本物の',chinese:'真实的',french:'authentique',spanish:'genuino',german:'echt',category:'adjective',difficulty:3},
  {id:'w1312',english:'adapt',korean:'적응하다',japanese:'適応する',chinese:'适应',french:'adapter',spanish:'adaptar',german:'anpassen',category:'action',difficulty:3},
  {id:'w1313',english:'adopt',korean:'채택하다',japanese:'採用する',chinese:'采纳',french:'adopter',spanish:'adoptar',german:'adoptieren',category:'action',difficulty:3},
  {id:'w1314',english:'occupy',korean:'차지하다',japanese:'占める',chinese:'占据',french:'occuper',spanish:'ocupar',german:'besetzen',category:'action',difficulty:3},
  {id:'w1315',english:'possess',korean:'소유하다',japanese:'所有する',chinese:'拥有',french:'posséder',spanish:'poseer',german:'besitzen',category:'action',difficulty:3},
  {id:'w1316',english:'prohibit',korean:'금지하다',japanese:'禁止する',chinese:'禁止',french:'interdire',spanish:'prohibir',german:'verbieten',category:'action',difficulty:3},
  {id:'w1317',english:'propose',korean:'제안하다',japanese:'提案する',chinese:'提议',french:'proposer',spanish:'proponer',german:'vorschlagen',category:'action',difficulty:3},
  {id:'w1318',english:'require',korean:'요구하다',japanese:'要求する',chinese:'要求',french:'exiger',spanish:'requerir',german:'erfordern',category:'action',difficulty:3},
  {id:'w1319',english:'resign',korean:'사임하다',japanese:'辞任する',chinese:'辞职',french:'démissionner',spanish:'renunciar',german:'zurücktreten',category:'action',difficulty:3},
  {id:'w1320',english:'reveal',korean:'드러내다',japanese:'明らかにする',chinese:'揭示',french:'révéler',spanish:'revelar',german:'enthüllen',category:'action',difficulty:3},
  {id:'w1321',english:'strategy',korean:'전략',japanese:'戦略',chinese:'策略',french:'stratégie',spanish:'estrategia',german:'Strategie',category:'abstract',difficulty:3},
  {id:'w1322',english:'perspective',korean:'관점',japanese:'視点',chinese:'视角',french:'perspective',spanish:'perspectiva',german:'Perspektive',category:'abstract',difficulty:3},
  {id:'w1323',english:'reputation',korean:'명성',japanese:'評判',chinese:'名誉',french:'réputation',spanish:'reputación',german:'Ruf',category:'abstract',difficulty:3},
  {id:'w1324',english:'priority',korean:'우선순위',japanese:'優先事項',chinese:'优先',french:'priorité',spanish:'prioridad',german:'Priorität',category:'abstract',difficulty:3},
  {id:'w1325',english:'potential',korean:'잠재력',japanese:'可能性',chinese:'潜力',french:'potentiel',spanish:'potencial',german:'Potenzial',category:'abstract',difficulty:3},
  {id:'w1326',english:'obstacle',korean:'장애물',japanese:'障害物',chinese:'障碍',french:'obstacle',spanish:'obstáculo',german:'Hindernis',category:'abstract',difficulty:3},
  {id:'w1327',english:'phenomenon',korean:'현상',japanese:'現象',chinese:'现象',french:'phénomène',spanish:'fenómeno',german:'Phänomen',category:'abstract',difficulty:3},
  {id:'w1328',english:'circumstance',korean:'상황',japanese:'状況',chinese:'情况',french:'circonstance',spanish:'circunstancia',german:'Umstand',category:'abstract',difficulty:3},
  {id:'w1329',english:'contrast',korean:'대조',japanese:'対比',chinese:'对比',french:'contraste',spanish:'contraste',german:'Kontrast',category:'abstract',difficulty:3},
  {id:'w1330',english:'aspect',korean:'측면',japanese:'側面',chinese:'方面',french:'aspect',spanish:'aspecto',german:'Aspekt',category:'abstract',difficulty:3},
  {id:'w1331',english:'context',korean:'맥락',japanese:'文脈',chinese:'背景',french:'contexte',spanish:'contexto',german:'Kontext',category:'abstract',difficulty:3},
  {id:'w1332',english:'outcome',korean:'결과',japanese:'結果',chinese:'结果',french:'résultat',spanish:'resultado',german:'Ergebnis',category:'abstract',difficulty:3},
];

// ============================================================
// LEVEL 4 NEW WORDS (w1333-w1482) - 150 words for 6th graders
// All duplicates replaced with unique words
// ============================================================
const level4New = [
  {id:'w1333',english:'chromosome',korean:'염색체',japanese:'染色体',chinese:'染色体',french:'chromosome',spanish:'cromosoma',german:'Chromosom',category:'science',difficulty:4},
  {id:'w1334',english:'organism',korean:'유기체',japanese:'有機体',chinese:'有机体',french:'organisme',spanish:'organismo',german:'Organismus',category:'science',difficulty:4},
  {id:'w1335',english:'protein',korean:'단백질',japanese:'タンパク質',chinese:'蛋白质',french:'protéine',spanish:'proteína',german:'Protein',category:'science',difficulty:4},
  {id:'w1336',english:'enzyme',korean:'효소',japanese:'酵素',chinese:'酶',french:'enzyme',spanish:'enzima',german:'Enzym',category:'science',difficulty:4},
  {id:'w1337',english:'metabolism',korean:'신진대사',japanese:'新陳代謝',chinese:'新陈代谢',french:'métabolisme',spanish:'metabolismo',german:'Stoffwechsel',category:'science',difficulty:4},
  {id:'w1338',english:'compound',korean:'화합물',japanese:'化合物',chinese:'化合物',french:'composé',spanish:'compuesto',german:'Verbindung',category:'science',difficulty:4},
  {id:'w1339',english:'reaction',korean:'반응',japanese:'反応',chinese:'反应',french:'réaction',spanish:'reacción',german:'Reaktion',category:'science',difficulty:4},
  {id:'w1340',english:'dissolve',korean:'녹이다',japanese:'溶かす',chinese:'溶解',french:'dissoudre',spanish:'disolver',german:'auflösen',category:'science',difficulty:4},
  {id:'w1341',english:'evaporate',korean:'증발하다',japanese:'蒸発する',chinese:'蒸发',french:'évaporer',spanish:'evaporar',german:'verdunsten',category:'science',difficulty:4},
  {id:'w1342',english:'condense',korean:'응축하다',japanese:'凝縮する',chinese:'凝结',french:'condenser',spanish:'condensar',german:'kondensieren',category:'science',difficulty:4},
  {id:'w1343',english:'velocity',korean:'속도',japanese:'速度',chinese:'速度',french:'vélocité',spanish:'velocidad',german:'Geschwindigkeit',category:'science',difficulty:4},
  {id:'w1344',english:'density',korean:'밀도',japanese:'密度',chinese:'密度',french:'densité',spanish:'densidad',german:'Dichte',category:'science',difficulty:4},
  {id:'w1345',english:'spectrum',korean:'스펙트럼',japanese:'スペクトル',chinese:'光谱',french:'spectre',spanish:'espectro',german:'Spektrum',category:'science',difficulty:4},
  {id:'w1346',english:'synthesis',korean:'합성',japanese:'合成',chinese:'合成',french:'synthèse',spanish:'síntesis',german:'Synthese',category:'science',difficulty:4},
  {id:'w1347',english:'catalyst',korean:'촉매',japanese:'触媒',chinese:'催化剂',french:'catalyseur',spanish:'catalizador',german:'Katalysator',category:'science',difficulty:4},
  {id:'w1348',english:'parliament',korean:'의회',japanese:'議会',chinese:'议会',french:'parlement',spanish:'parlamento',german:'Parlament',category:'society',difficulty:4},
  {id:'w1349',english:'amendment',korean:'수정안',japanese:'修正',chinese:'修正案',french:'amendement',spanish:'enmienda',german:'Änderung',category:'society',difficulty:4},
  {id:'w1350',english:'citizenship',korean:'시민권',japanese:'市民権',chinese:'公民权',french:'citoyenneté',spanish:'ciudadanía',german:'Staatsbürgerschaft',category:'society',difficulty:4},
  {id:'w1351',english:'revolution',korean:'혁명',japanese:'革命',chinese:'革命',french:'révolution',spanish:'revolución',german:'Revolution',category:'society',difficulty:4},
  {id:'w1352',english:'diplomacy',korean:'외교',japanese:'外交',chinese:'外交',french:'diplomatie',spanish:'diplomacia',german:'Diplomatie',category:'society',difficulty:4},
  {id:'w1353',english:'sovereignty',korean:'주권',japanese:'主権',chinese:'主权',french:'souveraineté',spanish:'soberanía',german:'Souveränität',category:'society',difficulty:4},
  {id:'w1354',english:'colonial',korean:'식민지의',japanese:'植民地の',chinese:'殖民的',french:'colonial',spanish:'colonial',german:'kolonial',category:'society',difficulty:4},
  {id:'w1355',english:'capitalism',korean:'자본주의',japanese:'資本主義',chinese:'资本主义',french:'capitalisme',spanish:'capitalismo',german:'Kapitalismus',category:'society',difficulty:4},
  {id:'w1356',english:'socialism',korean:'사회주의',japanese:'社会主義',chinese:'社会主义',french:'socialisme',spanish:'socialismo',german:'Sozialismus',category:'society',difficulty:4},
  {id:'w1357',english:'sanction',korean:'제재',japanese:'制裁',chinese:'制裁',french:'sanction',spanish:'sanción',german:'Sanktion',category:'society',difficulty:4},
  {id:'w1358',english:'bureaucracy',korean:'관료제',japanese:'官僚制',chinese:'官僚制',french:'bureaucratie',spanish:'burocracia',german:'Bürokratie',category:'society',difficulty:4},
  {id:'w1359',english:'propaganda',korean:'선전',japanese:'プロパガンダ',chinese:'宣传',french:'propagande',spanish:'propaganda',german:'Propaganda',category:'society',difficulty:4},
  {id:'w1360',english:'petition',korean:'청원',japanese:'請願',chinese:'请愿',french:'pétition',spanish:'petición',german:'Petition',category:'society',difficulty:4},
  {id:'w1361',english:'tyranny',korean:'폭정',japanese:'暴政',chinese:'暴政',french:'tyrannie',spanish:'tiranía',german:'Tyrannei',category:'society',difficulty:4},
  {id:'w1362',english:'monarchy',korean:'군주제',japanese:'君主制',chinese:'君主制',french:'monarchie',spanish:'monarquía',german:'Monarchie',category:'society',difficulty:4},
  {id:'w1363',english:'autobiography',korean:'자서전',japanese:'自伝',chinese:'自传',french:'autobiographie',spanish:'autobiografía',german:'Autobiografie',category:'academic',difficulty:4},
  {id:'w1364',english:'nonfiction',korean:'논픽션',japanese:'ノンフィクション',chinese:'非虚构',french:'non-fiction',spanish:'no ficción',german:'Sachbuch',category:'academic',difficulty:4},
  {id:'w1365',english:'metaphor',korean:'은유',japanese:'比喩',chinese:'隐喻',french:'métaphore',spanish:'metáfora',german:'Metapher',category:'academic',difficulty:4},
  {id:'w1366',english:'symbolism',korean:'상징주의',japanese:'象徴主義',chinese:'象征主义',french:'symbolisme',spanish:'simbolismo',german:'Symbolismus',category:'academic',difficulty:4},
  {id:'w1367',english:'protagonist',korean:'주인공',japanese:'主人公',chinese:'主角',french:'protagoniste',spanish:'protagonista',german:'Protagonist',category:'academic',difficulty:4},
  {id:'w1368',english:'anthology',korean:'선집',japanese:'アンソロジー',chinese:'选集',french:'anthologie',spanish:'antología',german:'Anthologie',category:'academic',difficulty:4},
  {id:'w1369',english:'genre',korean:'장르',japanese:'ジャンル',chinese:'体裁',french:'genre',spanish:'género',german:'Genre',category:'academic',difficulty:4},
  {id:'w1370',english:'prologue',korean:'서문',japanese:'プロローグ',chinese:'序言',french:'prologue',spanish:'prólogo',german:'Prolog',category:'academic',difficulty:4},
  {id:'w1371',english:'epilogue',korean:'에필로그',japanese:'エピローグ',chinese:'尾声',french:'épilogue',spanish:'epílogo',german:'Epilog',category:'academic',difficulty:4},
  {id:'w1372',english:'satire',korean:'풍자',japanese:'風刺',chinese:'讽刺',french:'satire',spanish:'sátira',german:'Satire',category:'academic',difficulty:4},
  {id:'w1373',english:'equation',korean:'방정식',japanese:'方程式',chinese:'方程式',french:'équation',spanish:'ecuación',german:'Gleichung',category:'academic',difficulty:4},
  {id:'w1374',english:'fraction',korean:'분수',japanese:'分数',chinese:'分数',french:'fraction',spanish:'fracción',german:'Bruch',category:'academic',difficulty:4},
  {id:'w1375',english:'percentage',korean:'백분율',japanese:'パーセント',chinese:'百分比',french:'pourcentage',spanish:'porcentaje',german:'Prozentsatz',category:'academic',difficulty:4},
  {id:'w1376',english:'geometry',korean:'기하학',japanese:'幾何学',chinese:'几何学',french:'géométrie',spanish:'geometría',german:'Geometrie',category:'academic',difficulty:4},
  {id:'w1377',english:'diameter',korean:'지름',japanese:'直径',chinese:'直径',french:'diamètre',spanish:'diámetro',german:'Durchmesser',category:'academic',difficulty:4},
  {id:'w1378',english:'circumference',korean:'둘레',japanese:'円周',chinese:'周长',french:'circonférence',spanish:'circunferencia',german:'Umfang',category:'academic',difficulty:4},
  {id:'w1379',english:'probability',korean:'확률',japanese:'確率',chinese:'概率',french:'probabilité',spanish:'probabilidad',german:'Wahrscheinlichkeit',category:'academic',difficulty:4},
  {id:'w1380',english:'statistics',korean:'통계',japanese:'統計',chinese:'统计',french:'statistiques',spanish:'estadísticas',german:'Statistik',category:'academic',difficulty:4},
  {id:'w1381',english:'variable',korean:'변수',japanese:'変数',chinese:'变量',french:'variable',spanish:'variable',german:'Variable',category:'academic',difficulty:4},
  {id:'w1382',english:'ratio',korean:'비율',japanese:'比率',chinese:'比率',french:'ratio',spanish:'proporción',german:'Verhältnis',category:'academic',difficulty:4},
  {id:'w1383',english:'summarize',korean:'요약하다',japanese:'要約する',chinese:'总结',french:'résumer',spanish:'resumir',german:'zusammenfassen',category:'action',difficulty:4},
  {id:'w1384',english:'synthesize',korean:'종합하다',japanese:'統合する',chinese:'综合',french:'synthétiser',spanish:'sintetizar',german:'synthetisieren',category:'action',difficulty:4},
  {id:'w1385',english:'emphasize',korean:'강조하다',japanese:'強調する',chinese:'强调',french:'souligner',spanish:'enfatizar',german:'betonen',category:'action',difficulty:4},
  {id:'w1386',english:'undermine',korean:'약화시키다',japanese:'弱体化させる',chinese:'削弱',french:'saper',spanish:'socavar',german:'untergraben',category:'action',difficulty:4},
  {id:'w1387',english:'speculate',korean:'추측하다',japanese:'推測する',chinese:'推测',french:'spéculer',spanish:'especular',german:'spekulieren',category:'action',difficulty:4},
  {id:'w1388',english:'distinguish',korean:'구별하다',japanese:'区別する',chinese:'区分',french:'distinguer',spanish:'distinguir',german:'unterscheiden',category:'action',difficulty:4},
  {id:'w1389',english:'compensate',korean:'보상하다',japanese:'補償する',chinese:'补偿',french:'compenser',spanish:'compensar',german:'kompensieren',category:'action',difficulty:4},
  {id:'w1390',english:'simulate',korean:'모의 실험하다',japanese:'シミュレーションする',chinese:'模拟',french:'simuler',spanish:'simular',german:'simulieren',category:'action',difficulty:4},
  {id:'w1391',english:'reinforce',korean:'강화하다',japanese:'強化する',chinese:'强化',french:'renforcer',spanish:'reforzar',german:'verstärken',category:'action',difficulty:4},
  {id:'w1392',english:'modify',korean:'수정하다',japanese:'修正する',chinese:'修改',french:'modifier',spanish:'modificar',german:'modifizieren',category:'action',difficulty:4},
  {id:'w1393',english:'violate',korean:'위반하다',japanese:'違反する',chinese:'违反',french:'violer',spanish:'violar',german:'verletzen',category:'action',difficulty:4},
  {id:'w1394',english:'suspend',korean:'중단하다',japanese:'一時停止する',chinese:'暂停',french:'suspendre',spanish:'suspender',german:'aussetzen',category:'action',difficulty:4},
  {id:'w1395',english:'diminish',korean:'줄이다',japanese:'減少させる',chinese:'减少',french:'diminuer',spanish:'disminuir',german:'vermindern',category:'action',difficulty:4},
  {id:'w1396',english:'provoke',korean:'도발하다',japanese:'挑発する',chinese:'激怒',french:'provoquer',spanish:'provocar',german:'provozieren',category:'action',difficulty:4},
  {id:'w1397',english:'suppress',korean:'억압하다',japanese:'抑圧する',chinese:'压制',french:'supprimer',spanish:'suprimir',german:'unterdrücken',category:'action',difficulty:4},
  {id:'w1398',english:'controversial',korean:'논쟁적인',japanese:'議論を呼ぶ',chinese:'有争议的',french:'controversé',spanish:'controvertido',german:'umstritten',category:'adjective',difficulty:4},
  {id:'w1399',english:'substantial',korean:'상당한',japanese:'実質的な',chinese:'实质性的',french:'substantiel',spanish:'sustancial',german:'wesentlich',category:'adjective',difficulty:4},
  {id:'w1400',english:'inevitable',korean:'불가피한',japanese:'避けられない',chinese:'不可避免的',french:'inévitable',spanish:'inevitable',german:'unvermeidlich',category:'adjective',difficulty:4},
  {id:'w1401',english:'sophisticated',korean:'정교한',japanese:'洗練された',chinese:'复杂精密的',french:'sophistiqué',spanish:'sofisticado',german:'anspruchsvoll',category:'adjective',difficulty:4},
  {id:'w1402',english:'preliminary',korean:'예비의',japanese:'予備的な',chinese:'初步的',french:'préliminaire',spanish:'preliminar',german:'vorläufig',category:'adjective',difficulty:4},
  {id:'w1403',english:'subsequent',korean:'그 이후의',japanese:'その後の',chinese:'随后的',french:'ultérieur',spanish:'subsiguiente',german:'nachfolgend',category:'adjective',difficulty:4},
  {id:'w1404',english:'simultaneous',korean:'동시의',japanese:'同時の',chinese:'同时的',french:'simultané',spanish:'simultáneo',german:'gleichzeitig',category:'adjective',difficulty:4},
  {id:'w1405',english:'ambiguous',korean:'모호한',japanese:'曖昧な',chinese:'模糊的',french:'ambigu',spanish:'ambiguo',german:'mehrdeutig',category:'adjective',difficulty:4},
  {id:'w1406',english:'authentic',korean:'진정한',japanese:'本物の',chinese:'真正的',french:'authentique',spanish:'auténtico',german:'authentisch',category:'adjective',difficulty:4},
  {id:'w1407',english:'autonomous',korean:'자율적인',japanese:'自律的な',chinese:'自主的',french:'autonome',spanish:'autónomo',german:'autonom',category:'adjective',difficulty:4},
  {id:'w1408',english:'compatible',korean:'호환되는',japanese:'互換性のある',chinese:'兼容的',french:'compatible',spanish:'compatible',german:'kompatibel',category:'adjective',difficulty:4},
  {id:'w1409',english:'explicit',korean:'명시적인',japanese:'明示的な',chinese:'明确的',french:'explicite',spanish:'explícito',german:'explizit',category:'adjective',difficulty:4},
  {id:'w1410',english:'implicit',korean:'암시적인',japanese:'暗黙の',chinese:'隐含的',french:'implicite',spanish:'implícito',german:'implizit',category:'adjective',difficulty:4},
  {id:'w1411',english:'radical',korean:'급진적인',japanese:'急進的な',chinese:'激进的',french:'radical',spanish:'radical',german:'radikal',category:'adjective',difficulty:4},
  {id:'w1412',english:'mutual',korean:'상호의',japanese:'相互の',chinese:'相互的',french:'mutuel',spanish:'mutuo',german:'gegenseitig',category:'adjective',difficulty:4},
  {id:'w1413',english:'immigration',korean:'이민',japanese:'移民',chinese:'移民',french:'immigration',spanish:'inmigración',german:'Einwanderung',category:'society',difficulty:4},
  {id:'w1414',english:'refugee',korean:'난민',japanese:'難民',chinese:'难民',french:'réfugié',spanish:'refugiado',german:'Flüchtling',category:'society',difficulty:4},
  {id:'w1415',english:'inequality',korean:'불평등',japanese:'不平等',chinese:'不平等',french:'inégalité',spanish:'desigualdad',german:'Ungleichheit',category:'society',difficulty:4},
  {id:'w1416',english:'sustainability',korean:'지속 가능성',japanese:'持続可能性',chinese:'可持续性',french:'durabilité',spanish:'sostenibilidad',german:'Nachhaltigkeit',category:'society',difficulty:4},
  {id:'w1417',english:'globalization',korean:'세계화',japanese:'グローバル化',chinese:'全球化',french:'mondialisation',spanish:'globalización',german:'Globalisierung',category:'society',difficulty:4},
  {id:'w1418',english:'pandemic',korean:'팬데믹',japanese:'パンデミック',chinese:'大流行',french:'pandémie',spanish:'pandemia',german:'Pandemie',category:'society',difficulty:4},
  {id:'w1419',english:'humanitarian',korean:'인도주의적',japanese:'人道的な',chinese:'人道主义的',french:'humanitaire',spanish:'humanitario',german:'humanitär',category:'society',difficulty:4},
  {id:'w1420',english:'corruption',korean:'부패',japanese:'腐敗',chinese:'腐败',french:'corruption',spanish:'corrupción',german:'Korruption',category:'society',difficulty:4},
  {id:'w1421',english:'terrorism',korean:'테러리즘',japanese:'テロリズム',chinese:'恐怖主义',french:'terrorisme',spanish:'terrorismo',german:'Terrorismus',category:'society',difficulty:4},
  {id:'w1422',english:'famine',korean:'기근',japanese:'飢饉',chinese:'饥荒',french:'famine',spanish:'hambruna',german:'Hungersnot',category:'society',difficulty:4},
  {id:'w1423',english:'biodiversity',korean:'생물 다양성',japanese:'生物多様性',chinese:'生物多样性',french:'biodiversité',spanish:'biodiversidad',german:'Biodiversität',category:'science',difficulty:4},
  {id:'w1424',english:'urbanization',korean:'도시화',japanese:'都市化',chinese:'城市化',french:'urbanisation',spanish:'urbanización',german:'Urbanisierung',category:'society',difficulty:4},
  {id:'w1425',english:'censorship',korean:'검열',japanese:'検閲',chinese:'审查',french:'censure',spanish:'censura',german:'Zensur',category:'society',difficulty:4},
  {id:'w1426',english:'philosophy',korean:'철학',japanese:'哲学',chinese:'哲学',french:'philosophie',spanish:'filosofía',german:'Philosophie',category:'abstract',difficulty:4},
  {id:'w1427',english:'theory',korean:'이론',japanese:'理論',chinese:'理论',french:'théorie',spanish:'teoría',german:'Theorie',category:'abstract',difficulty:4},
  {id:'w1428',english:'paradox',korean:'역설',japanese:'パラドックス',chinese:'悖论',french:'paradoxe',spanish:'paradoja',german:'Paradox',category:'abstract',difficulty:4},
  {id:'w1429',english:'ethics',korean:'윤리학',japanese:'倫理学',chinese:'伦理学',french:'éthique',spanish:'ética',german:'Ethik',category:'abstract',difficulty:4},
  {id:'w1430',english:'morality',korean:'도덕성',japanese:'道徳',chinese:'道德',french:'moralité',spanish:'moralidad',german:'Moral',category:'abstract',difficulty:4},
  {id:'w1431',english:'virtue',korean:'미덕',japanese:'美徳',chinese:'美德',french:'vertu',spanish:'virtud',german:'Tugend',category:'abstract',difficulty:4},
  {id:'w1432',english:'identity',korean:'정체성',japanese:'アイデンティティ',chinese:'身份',french:'identité',spanish:'identidad',german:'Identität',category:'abstract',difficulty:4},
  {id:'w1433',english:'prejudice',korean:'편견',japanese:'偏見',chinese:'偏见',french:'préjugé',spanish:'prejuicio',german:'Vorurteil',category:'abstract',difficulty:4},
  {id:'w1434',english:'stereotype',korean:'고정관념',japanese:'固定観念',chinese:'刻板印象',french:'stéréotype',spanish:'estereotipo',german:'Stereotyp',category:'abstract',difficulty:4},
  {id:'w1435',english:'consciousness',korean:'의식',japanese:'意識',chinese:'意识',french:'conscience',spanish:'conciencia',german:'Bewusstsein',category:'abstract',difficulty:4},
  {id:'w1436',english:'allegiance',korean:'충성',japanese:'忠誠',chinese:'忠诚',french:'allégeance',spanish:'lealtad',german:'Treue',category:'abstract',difficulty:4},
  {id:'w1437',english:'analogy',korean:'유추',japanese:'類推',chinese:'类比',french:'analogie',spanish:'analogía',german:'Analogie',category:'abstract',difficulty:4},
  {id:'w1438',english:'anecdote',korean:'일화',japanese:'逸話',chinese:'轶事',french:'anecdote',spanish:'anécdota',german:'Anekdote',category:'abstract',difficulty:4},
  {id:'w1439',english:'arbitrary',korean:'임의적인',japanese:'任意の',chinese:'任意的',french:'arbitraire',spanish:'arbitrario',german:'willkürlich',category:'adjective',difficulty:4},
  {id:'w1440',english:'benevolent',korean:'자비로운',japanese:'慈悲深い',chinese:'仁慈的',french:'bienveillant',spanish:'benévolo',german:'wohlwollend',category:'adjective',difficulty:4},
  {id:'w1441',english:'coherent',korean:'일관된',japanese:'首尾一貫した',chinese:'连贯的',french:'cohérent',spanish:'coherente',german:'kohärent',category:'adjective',difficulty:4},
  {id:'w1442',english:'unanimous',korean:'만장일치의',japanese:'満場一致の',chinese:'一致的',french:'unanime',spanish:'unánime',german:'einstimmig',category:'adjective',difficulty:4},
  {id:'w1443',english:'semiconductor',korean:'반도체',japanese:'半導体',chinese:'半导体',french:'semi-conducteur',spanish:'semiconductor',german:'Halbleiter',category:'technology',difficulty:4},
  {id:'w1444',english:'telecommunication',korean:'통신',japanese:'通信',chinese:'电信',french:'télécommunication',spanish:'telecomunicación',german:'Telekommunikation',category:'technology',difficulty:4},
  {id:'w1445',english:'navigate',korean:'항해하다',japanese:'航行する',chinese:'导航',french:'naviguer',spanish:'navegar',german:'navigieren',category:'technology',difficulty:4},
  {id:'w1446',english:'encryption',korean:'암호화',japanese:'暗号化',chinese:'加密',french:'cryptage',spanish:'cifrado',german:'Verschlüsselung',category:'technology',difficulty:4},
  {id:'w1447',english:'prototype',korean:'원형',japanese:'プロトタイプ',chinese:'原型',french:'prototype',spanish:'prototipo',german:'Prototyp',category:'technology',difficulty:4},
  {id:'w1448',english:'thesis',korean:'논문',japanese:'論文',chinese:'论文',french:'thèse',spanish:'tesis',german:'These',category:'academic',difficulty:4},
  {id:'w1449',english:'citation',korean:'인용',japanese:'引用',chinese:'引用',french:'citation',spanish:'cita',german:'Zitat',category:'academic',difficulty:4},
  {id:'w1450',english:'paradigm',korean:'패러다임',japanese:'パラダイム',chinese:'范式',french:'paradigme',spanish:'paradigma',german:'Paradigma',category:'academic',difficulty:4},
  {id:'w1451',english:'jurisdiction',korean:'관할권',japanese:'管轄権',chinese:'管辖权',french:'juridiction',spanish:'jurisdicción',german:'Gerichtsbarkeit',category:'society',difficulty:4},
  {id:'w1452',english:'referendum',korean:'국민투표',japanese:'国民投票',chinese:'公投',french:'référendum',spanish:'referéndum',german:'Referendum',category:'society',difficulty:4},
  {id:'w1453',english:'veto',korean:'거부권',japanese:'拒否権',chinese:'否决权',french:'véto',spanish:'veto',german:'Veto',category:'society',difficulty:4},
  {id:'w1454',english:'subsidy',korean:'보조금',japanese:'補助金',chinese:'补贴',french:'subvention',spanish:'subsidio',german:'Subvention',category:'society',difficulty:4},
  {id:'w1455',english:'tariff',korean:'관세',japanese:'関税',chinese:'关税',french:'tarif',spanish:'arancel',german:'Zoll',category:'society',difficulty:4},
  {id:'w1456',english:'deficit',korean:'적자',japanese:'赤字',chinese:'赤字',french:'déficit',spanish:'déficit',german:'Defizit',category:'society',difficulty:4},
  {id:'w1457',english:'inflation',korean:'인플레이션',japanese:'インフレーション',chinese:'通货膨胀',french:'inflation',spanish:'inflación',german:'Inflation',category:'society',difficulty:4},
  {id:'w1458',english:'recession',korean:'불황',japanese:'不況',chinese:'经济衰退',french:'récession',spanish:'recesión',german:'Rezession',category:'society',difficulty:4},
  {id:'w1459',english:'prosperity',korean:'번영',japanese:'繁栄',chinese:'繁荣',french:'prospérité',spanish:'prosperidad',german:'Wohlstand',category:'abstract',difficulty:4},
  {id:'w1460',english:'mediator',korean:'중재자',japanese:'調停者',chinese:'调解人',french:'médiateur',spanish:'mediador',german:'Vermittler',category:'society',difficulty:4},
  {id:'w1461',english:'testimony',korean:'증언',japanese:'証言',chinese:'证词',french:'témoignage',spanish:'testimonio',german:'Aussage',category:'society',difficulty:4},
  {id:'w1462',english:'allegation',korean:'주장',japanese:'申し立て',chinese:'指控',french:'allégation',spanish:'alegación',german:'Behauptung',category:'society',difficulty:4},
  {id:'w1463',english:'prosecution',korean:'기소',japanese:'起訴',chinese:'起诉',french:'poursuite',spanish:'acusación',german:'Strafverfolgung',category:'society',difficulty:4},
  {id:'w1464',english:'verdict',korean:'판결',japanese:'評決',chinese:'判决',french:'verdict',spanish:'veredicto',german:'Urteil',category:'society',difficulty:4},
  {id:'w1465',english:'acquit',korean:'무죄 선고하다',japanese:'無罪とする',chinese:'宣告无罪',french:'acquitter',spanish:'absolver',german:'freisprechen',category:'action',difficulty:4},
  {id:'w1466',english:'abolish',korean:'폐지하다',japanese:'廃止する',chinese:'废除',french:'abolir',spanish:'abolir',german:'abschaffen',category:'action',difficulty:4},
  {id:'w1467',english:'amend',korean:'개정하다',japanese:'修正する',chinese:'修改',french:'amender',spanish:'enmendar',german:'ändern',category:'action',difficulty:4},
  {id:'w1468',english:'ratify',korean:'비준하다',japanese:'批准する',chinese:'批准',french:'ratifier',spanish:'ratificar',german:'ratifizieren',category:'action',difficulty:4},
  {id:'w1469',english:'prevail',korean:'우세하다',japanese:'勝つ',chinese:'盛行',french:'prévaloir',spanish:'prevalecer',german:'vorherrschen',category:'action',difficulty:4},
  {id:'w1470',english:'scrutinize',korean:'면밀히 조사하다',japanese:'精査する',chinese:'仔细审查',french:'scruter',spanish:'escrutar',german:'prüfen',category:'action',difficulty:4},
  {id:'w1471',english:'transcend',korean:'초월하다',japanese:'超越する',chinese:'超越',french:'transcender',spanish:'trascender',german:'übersteigen',category:'action',difficulty:4},
  {id:'w1472',english:'perpetuate',korean:'영속시키다',japanese:'永続させる',chinese:'使永久化',french:'perpétuer',spanish:'perpetuar',german:'fortsetzen',category:'action',difficulty:4},
  {id:'w1473',english:'alleviate',korean:'완화하다',japanese:'緩和する',chinese:'减轻',french:'alléger',spanish:'aliviar',german:'lindern',category:'action',difficulty:4},
  {id:'w1474',english:'exacerbate',korean:'악화시키다',japanese:'悪化させる',chinese:'加剧',french:'exacerber',spanish:'exacerbar',german:'verschlimmern',category:'action',difficulty:4},
  {id:'w1475',english:'unanimous',korean:'만장일치로',japanese:'全会一致で',chinese:'全体一致',french:'à l\'unanimité',spanish:'unánimemente',german:'einstimmig',category:'adjective',difficulty:4},
  {id:'w1476',english:'pragmatic',korean:'실용적인',japanese:'実用的な',chinese:'务实的',french:'pragmatique',spanish:'pragmático',german:'pragmatisch',category:'adjective',difficulty:4},
  {id:'w1477',english:'resilient',korean:'회복력 있는',japanese:'回復力のある',chinese:'有韧性的',french:'résilient',spanish:'resiliente',german:'widerstandsfähig',category:'adjective',difficulty:4},
  {id:'w1478',english:'paradoxical',korean:'역설적인',japanese:'逆説的な',chinese:'矛盾的',french:'paradoxal',spanish:'paradójico',german:'paradox',category:'adjective',difficulty:4},
  {id:'w1479',english:'meticulous',korean:'꼼꼼한',japanese:'几帳面な',chinese:'一丝不苟的',french:'méticuleux',spanish:'meticuloso',german:'akribisch',category:'adjective',difficulty:4},
  {id:'w1480',english:'prolific',korean:'다작의',japanese:'多作の',chinese:'多产的',french:'prolifique',spanish:'prolífico',german:'produktiv',category:'adjective',difficulty:4},
  {id:'w1481',english:'tentative',korean:'잠정적인',japanese:'暫定的な',chinese:'暂定的',french:'provisoire',spanish:'tentativo',german:'vorläufig',category:'adjective',difficulty:4},
  {id:'w1482',english:'unprecedented',korean:'전례 없는',japanese:'前例のない',chinese:'史无前例的',french:'sans précédent',spanish:'sin precedentes',german:'beispiellos',category:'adjective',difficulty:4},
];

// ============================================================
// VALIDATE: check no duplicates
// ============================================================
function checkDuplicates(newWords, levelName, tracker) {
  let dupeCount = 0;
  for (const w of newWords) {
    const key = w.english.toLowerCase();
    if (tracker.has(key)) {
      console.warn(`DUPLICATE in ${levelName}: "${w.english}" already exists`);
      dupeCount++;
    }
    tracker.add(key);
  }
  return dupeCount;
}

const tracker = new Set(allExisting);
let totalDupes = 0;
totalDupes += checkDuplicates(level2New, 'Level 2', tracker);
totalDupes += checkDuplicates(level3New, 'Level 3', tracker);
totalDupes += checkDuplicates(level4New, 'Level 4', tracker);

if (totalDupes > 0) {
  console.error(`\nFOUND ${totalDupes} DUPLICATES - ABORTING!`);
  process.exit(1);
}

// Append
data.levels['2'].words.push(...level2New);
data.levels['3'].words.push(...level3New);
data.levels['4'].words.push(...level4New);

console.log('\nFinal counts:');
console.log('Level 1:', data.levels['1'].words.length, 'words');
console.log('Level 2:', data.levels['2'].words.length, 'words (added', level2New.length, ')');
console.log('Level 3:', data.levels['3'].words.length, 'words (added', level3New.length, ')');
console.log('Level 4:', data.levels['4'].words.length, 'words (added', level4New.length, ')');

const total = Object.values(data.levels).reduce((sum, l) => sum + l.words.length, 0);
console.log('Total:', total, 'words');

// Write
fs.writeFileSync(vocabPath, JSON.stringify(data, null, 2), 'utf8');
console.log('\nSuccessfully wrote vocabulary.json');
